# Generated by Django 5.0.3 on 2024-03-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_movie_screen_theatre_show_screen_theatre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theatre_manager',
            old_name='adress',
            new_name='address',
        ),
    ]
