# Generated by Django 5.0.3 on 2024-03-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_user_user1'),
        ('main', '0013_booking_delete_booking1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User1',
            new_name='User',
        ),
    ]
