# Generated by Django 5.0.3 on 2024-03-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
    ]
