# Generated by Django 5.0.3 on 2024-03-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_booking_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
