# Generated by Django 5.0.3 on 2024-03-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_booking_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
