# Generated by Django 5.0.3 on 2024-03-30 13:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_delete_user'),
        ('main', '0014_alter_booking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='booking1',
        ),
    ]
